{
	"1": "Un error de script inesperado se ha encontrado en el método",
	"2": "Su conexión servidor no se ha probablemente liberado correctamente.",
	"3": "Imposible abrir una nueva sesión. Ningún dato recibido del servidor web.",
	"4": "Imposible abrir una nueva sesión. Datos inesperados se ha recibido del servidor web",
	"5": "Imposible recuperar el recurso en el servidor web.",
	"6": "Estado HTTP",
	"7": "Error HTTP.",
	"8": "Imposible recuperar los recursos compartidos en el servidor web. Su sesión se va a cerrar.",
	"9": "Un error inesperado se ha encontrado durante el envío de una petición con destino el servidor web.",
	"10": "Error de aplicación",
	"11": "El servidor se negó a establecer una nueva sesión. Detalle:",
	"12": "Por un motivo desconocido, el servidor se negó a establecer una nueva sesión.",
	"13": "Un error javascript inesperado se ha detectado. Su sesión se va a cerrar. Vuelva a conectarse de nuevo.",
	"14": "Un error inesperado se ha producido tras el envoi de una petición al servidor web.",
	"15": "Recuso:",
	"16": "Una excepción Javascript no capturada se ha producido. Su sessión se tiene que cerrar.",
	"17": "Imposible recuperar el error.",
	"18": "Si el problema persiste, pongase en contacto con su informático.",
	"19": "La respuesta del servidor es incompleta o inconsistente. La sesión no se puede establecer.",
	"20": "Un error bloqueante ha ocurrido durante el proceso de la última respuesta recibida (modo polling).",
	"21": "Un error inesperado se ha producido durante el proceso de la última respuesta recibida.",
	"22": "La petición se ha cancelado porque la operación actual ha caducado",
	"23": "Consulte el detalle técnico para obtener mayor información sobre el origen del problema.",
	"1003": "Conexión denegada sin ningún motivo",
	"1005": "El último mensaje enviado por el servidor no incluye la regle 'end'.",
	"siteLinkFunc": "Ir a la función",
	"stackT": "Pila de las llamadas",
	"missCnxStmt": "Propiedad siguiente ausente en la parametrización reenviada por el servidor"
}